### ISSUE TITLE
Create Hybrid Systems

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalSystems.jl#14]
[Hybrid systems](https://www.google.gr/search?q=hybrid+system+wikipedia&ie=utf-8&oe=utf-8&gws_rd=cr&ei=fQCDWbCqBsTqUuSbhPAP) are a special type of dynamical system that switches between being continuous and discrete. An example could be the bouncing ball.

It will probably be a tiny bit tricky to implement them, but it has to be made as general as possible.

One need to have 2 equations of motion, one for continuous and one for discrete. Then a callback type function has to be created that will stop the ODE solving of `DifferentialEquations` and switch to discrete evolution (until some other kind of callback stops or for a specified amount of steps... implementation will show the best way...).

**Comment by ChrisRackauckas** [comment]
`DifferentialEquations` already does hybrid systems through its event handling interface (and the jump problems help here as well). In fact, the bouncing ball is the documentation example: http://docs.juliadiffeq.org/latest/features/callback_functions.html#ContinuousCallback-Examples-1

**Comment by Datseris** [comment]
Yeap that was exactly what I was looking at when I wrote this issue. The bouncy ball.

One would most likely make a new type, subtype of `ContinuousDynamicalSystem` that would work exactly like `ContiniousDS` with simply an extra field called "callback" or something.

The  this would allow pretty clear and straight forward communication with DiffEq, since to establish this the only thing necessary is to have a `ODEProblem(ds::DynamicalSystem)` method.

**Comment by ChrisRackauckas** [comment]
Or you just add a callback keyword to your `ContiniousDS `?

**Comment by Datseris** [comment]
So that the field `callback` would always exist but by default would be initialized in e.g. `nothing` ? Does the ODE handle nothing? How is the representation of missing callbacks?

**Comment by ChrisRackauckas** [comment]
It handles nothing by using no callbacks. That's the default.

**Comment by Datseris** [comment]
Yeap. Awesome, this seems like the best idea!

**Comment by Datseris** [comment]
This issue was moved to JuliaDynamics/DynamicalSystemsBase.jl#5
