### ISSUE TITLE
`DynamicalSystemsBase` seems to be pinned to `v1.6`

### ISSUE THREAD

**Issue by navidcy** [JuliaDynamics/DynamicalSystems.jl#141]
Does this compat entry needs to be updated?

https://github.com/JuliaDynamics/DynamicalSystems.jl/blob/bd2fdc10fffb0df23845472b9b22f17a2265c3dc/Project.toml#L18

to, e.g., 

```Julia
DynamicalSystemsBase = "^1.8"
```
?

**Comment by navidcy** [comment]
On the other hand, `CompatHelper` seems to be finding `DynamicalSystemsBase v1.8.5` which seems weird to me... But anyways....

https://github.com/JuliaDynamics/DynamicalSystems.jl/runs/2861852780?check_suite_focus=true

**Comment by navidcy** [comment]
Seems like CompatHelper has spotted this:
https://github.com/JuliaDynamics/DynamicalSystems.jl/runs/2861852780?check_suite_focus=true
but how come it didn't open a PR?

**Comment by navidcy** [comment]
Note that the docs use the latest docstrings from `DynamicalSystemsBase.jl` since there is no compat entry restricting the version in `docs/Project.toml`.

**Comment by Datseris** [comment]
`DynamicalSystemsBase = "1.6"` is a lower bound. It allows all future versions as well, it is not pinning.

**Comment by Datseris** [comment]
https://pkgdocs.julialang.org/v1/compatibility/#Version-specifier-format

**Comment by navidcy** [comment]
Ok my bad :)
