### ISSUE TITLE
Basins of attraction not running using Poincare section

### ISSUE THREAD

**Issue by Mmarwan92** [JuliaDynamics/DynamicalSystems.jl#154]
Greetings,
while computing basins of attraction using Poincare section of Lorenz or Roessler. It hangs there and takes hours and hours fir very small interval like 
xg=yg=(-6.0, 6.0, length=10)  [ sorry for syntax if any ].

Even, the basin doesnt work for majority of values of parameter in Lorenz and Roessler etc.

**Comment by Datseris** [comment]
please provide a MWE: a small piece of code that runs and replicates the problem.

**Comment by Mmarwan92** [comment]
> hi, please provide a MWE: a small, self-contained piece of code that runs and replicates the problem. Saying "Poincare section of Lorenz or Roessler" is meaningless. These systems have several parameters and one can define an arbitrary Poincare section. Your problem could just as well be using inappropriate system parameters or hyperplanes and I cannot know this.

What if we fix all other parameters and use only one parameter for system

**Comment by awage** [comment]
You still have to obtain a valid Poincaré section. Try to represent your trajectory in 3D and set your Poincaré section accordingly. If there are several attractors then computing the basins makes sense. At any rate you still need to study a bit the system beforehand to know where are your attractors.

**Comment by Datseris** [comment]
The point is, we are still missing a **Minimal Working Example**, a piece of code that runs. Without it, there is nothing we can do or say.

**Comment by Datseris** [comment]
will reopen if we get a minimal working example.
