### ISSUE TITLE
Erroneous prediction of divergence of certain initial conditions 

### ISSUE THREAD

**Issue by Lucalino** [JuliaDynamics/DynamicalSystems.jl#159]
The algorithm seems to predict divergence (or convergence outside grid domain) for certain initial conditions inside the grid ranges which can be shown to converge to an attractor by looking at the trajectories. For the case shown below, the trajectory remains inside the defined grid at all times, i.e. it never leaves the grid domain while it approaches the attractor.

In this example, the grid spans the domain [0.0, 1.0] x [0.0, 72.0] x [0.0, 72.0] and an attractor is found at [0.452934, 47.4862, 47.6215].
The initial condition at basins[60, 90, 90] = -1 which corresponds to x = xg[50] = 0.5959595959595959, y = z = yg[80] = 64.72727272727273 is predicted to either diverge to infinity or to converge to some attractor outside the grid domain. However, as we can see from the trajectory plots, it evolves towards the known attractor inside the domain and never attains values outside the grid range.

```julia
using GLMakie
using OrdinaryDiffEq
using DynamicalSystems

function my_system(x, p, t)
    dx = (exp(0.22 * x[2] - 9.4) * (1.0 - x[1]^2) - 2.2 * tanh(10.0 * x[1] - 4.5) - 2.2) / 100.0
    dy = 2.2 * tanh(10.0 * x[1] - 4.5) + 2.2 - exp(0.22 * x[2] - 9.4) + (x[3] - x[2]) * 4.32
    dz = 3.0 - exp(0.22 * x[3] - 9.4) - (x[3] - x[2]) * 0.48
    return SVector(dx, dy, dz)
end

p = Dict(
)

xg = range(0.0, 1.0; length = 100)
yg = zg = range(0.0, 72.0; length = 100)
grid = (xg, yg, zg)

# Initial condition that is predicted to diverge but doesn't
x0 = xg[60]
y0 = yg[90]
z0 = zg[90] 

u0 = [x0, y0, z0]
ds = ContinuousDynamicalSystem(my_system, u0, p)

diffeq = (alg = Vern9(), adaptive = false, dt = 0.001, reltol = 1e-8, abstol = 1e-8)

tr = trajectory(ds, 50; diffeq...)
x, y, z = columns(tr)
t = collect(1:1:length(x))

# Trajectory plots that demonstrate the convergence within grid boundaries
fig = Figure()
ax1 = Axis(fig[1,1])
ax2 = Axis(fig[2,1])
ax3 = Axis(fig[3,1])
lines!(ax1, t, x)
lines!(ax2, t, y)
lines!(ax3, t, z)
ax1.ylabel = "x"
ax2.ylabel = "y"
ax3.ylabel = "z"
ax3.xlabel = "t"

basins, attractors = basins_of_attraction(grid, ds)
```
The initial condition chosen above is not the only one that is predicted wrongly, it is just one example.

![Screenshot 2021-11-01 at 16 43 13](https://user-images.githubusercontent.com/72014857/139700683-25bcd5a7-859f-4a37-ac94-011836ec3c85.png)

I used the following package versions:

```julia
  [608a59af] ChaosTools v2.5.0
  [5732040d] DelayEmbeddings v2.0.1
  [61744808] DynamicalSystems v2.1.2
  [6e36e845] DynamicalSystemsBase v2.3.2
  [ed8fcbec] Entropies v1.1.0
  [639c3291] RecurrenceAnalysis v1.6.1
```

I hope, the problem is not due to wrong handling on my part in which case I apologize.

**Comment by Datseris** [comment]
cc @awage

**Comment by Datseris** [comment]
what happens if you use the same `diffeq` arguments in `basins_of_attraction`? What's the result of `basins[60, 90, 90]`?

**Comment by awage** [comment]
Hi! 

Is there a reason why you don't want an adaptive method? Your system seems well behaved. 

One other thing: it seems that the steady state is sometimes slightly negative. This code worked for me (took 2 min to compute): 

```
xg = range(-0.1, 1.0; length = 30)
yg = zg = range(0.0, 72.0; length = 50)
grid = (xg, yg, zg)
x0 = xg[1]; y0 = yg[1]; z0 = zg[1]
u0 = [x0, y0, z0]
ds = ContinuousDynamicalSystem(my_system, u0, p)
diffeq = (alg = Vern9(), reltol = 1e-8, abstol = 1e-8)
basins, attractors = basins_of_attraction(grid, ds; diffeq = diffeq)
```

**Comment by Lucalino** [comment]
Hi awage,
I'm rather new to this whole topic... what do you mean by adaptive method? Is that something one can specify in `basins_of_attraction`or is it an alltogether different way of computing the initial conditions that converge to the stable fixed point?
Also, I am not sure what you mean by steady state. Are you talking about the fixed point or some transient behaviour that would become slightly negative? (In which case I would like to know for which initial condition this happens as I didn't find any.) 
When I execute the code you shared above, then I indeed get a basins-array full of ones (so it seems to work!) but I don't understand why I need to start my x-range at -0.1 instead of 0.0. Like, how is this different and makes the algorithm succeed?

**Comment by Datseris** [comment]
> I'm rather new to this whole topic... what do you mean by adaptive method?

https://en.wikipedia.org/wiki/Adaptive_step_size

> When I try to execute basins, attractors = basins_of_attraction(grid, ds; diffeq...) I get the following error message:

The correct syntax is `basins, attractors = basins_of_attraction(grid, ds; diffeq)`. The docs are wrong, I'll fix them.

 > understand why I need to start my x-range at -0.1 instead of 0.0. Like, how is this different and makes the algorithm succeed?

You would need to read our paper to get this point precisely. Summary: A trajectory that spends too much time outside the grid counts as diverging, even if later it comes back into the grid. In general, the number 1 troubleshooting method with `basins_of_attraction` is to increase the grid size, and then resolution, if things do not go as you expect them to. 

I'm closing this as the solution to the issue was "use larger grid".

**Comment by Lucalino** [comment]
Hm... ok. As I have read the paper, I was aware of this condition and precicely therefore I find this "solution" slightly weird as the trajectory of the initial condition in the issue description never even comes close to the edges of the grid. It is not obvious to me why grid size enlargement would help there. But I guess you know the algorithm and its peculiarities better.

**Comment by Datseris** [comment]
Okay, to get this right: you are claiming that an initial condition that _never leaves the defined grid_ still gets the value `-1`?  We really need to be sure about this, because if that's true, then it's a bug. This is what I will see if I run the script that you pasted initially?

**Comment by Lucalino** [comment]
Yes. If I am not mistaken then this is exactly what I meant.

**Comment by awage** [comment]
You are right, it is not the steady state that is outside the grid. You have a unique fixed point at (0.452934 ,47.4862,  47.6215). 

The transient sometimes stays outside the grid too long (I got x = -1e-6 when it was detected as lost). Having a larger grid avoid this.  If you want to allow long transient outside the grid increase the keyword `mx_chk_lost` to a larger value (maybe 100 is OK). 

This code works: 
```
xg = range(0., 1.0; length = 60)
yg = zg = range(0.0, 72.0; length = 100)
grid = (xg, yg, zg)
diffeq = (alg = Vern9(), reltol = 1e-8, abstol = 1e-8)
basins, attractors = basins_of_attraction(grid, ds; diffeq = diffeq, mx_chk_lost=100)
```

¡No bug!

**Comment by Datseris** [comment]
My understanding is that the user claimed that there are initial conditions that _never leave the grid_ yet still get mapped to `-1`. This is at least the claim in the code posted original, where the grid location [60,90,90] gets `-1` but the trajectory does not leave the grid. (To be fair, I haven't actually seen that `basins[60,90,90]` is `-1`. I haven't run the code yet, but will get around it on Friday)

**Comment by Lucalino** [comment]
@awage Did you verify that the initial codition [0.5959595959595959, 64.72727272727273, 64.72727272727273] gets lost? This was the example initial condition for which the plots show that it should never leave the grid.

**Comment by awage** [comment]
There are two separate problems: 
* long transient outside the grid (this is solved with the keyword `mx_chk_lost`) 
* Solver instabilities. 

Without the keyword `diffeq` the default solver seems to blow up at some initial conditions. I don't know if it is because of the solver or the default tolerances. Everything stays at home with the `Vern9()` solver. 

@Datseris, maybe it's a problem of the `step!` function of the `SimpleTsit5` solver. With `Tsit5()` the basins are OK.     

So your initial condition stays inside the grid and is detected correctly with the correct solver.

**Comment by Datseris** [comment]
Yeah, `SimpleATsit5` has difficulties that's true, but it is also not clear where they are and where to solve them. The point is that this integrator is as basic as possible and minimizes compilation time and lines of source code. Hence being the default. But it is also the "worst" solver for real scientific applications. So it shouldn't be used when accuracy matters, such as here.

When you compared the default solver with `Tsit5()`, were you sure you were using the same tolerances for both?

**Comment by Lucalino** [comment]
Great that it was solver-related in the end. So no bug in the method :) 
Should have thought about that earlier but overlooked the fact that I hadn't told the basins function to use Vern9...
Thanks for spending the time figuring this out!
