### ISSUE TITLE
Add possibility to give lyapunov convergence timeseries instead of only final value

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalSystems.jl#18]
For both the `lyapunovs` and `lyapunov`.

**Comment by Datseris** [comment]
For type-stability reasons, they have to be different functions.
Like `lyapunov_full` and `lyapunovs_full`.

**Comment by ChrisRackauckas** [comment]
Or value-type inputs

**Comment by Datseris** [comment]
You mean like `Val{}`? I don't like this, it would make it very ackward. Since there isn't any existing argument taht could be used like this, I would have to make an extra argument and say something like
"give `x1=2` for the timeseries" which seems weird for me!

**Comment by SebastianM-C** [comment]
I tried to add `lyapunov_full` in #19

**Comment by Datseris** [comment]
We still need the same for `lyapunovs` and also both for Discrete systems

**Comment by Datseris** [comment]
#36 made this possible for `lyapunov` for both discrete and continuous systems.

What is left is to do the same for `lyapunovs` (super easy)

**Comment by Datseris** [comment]
The only thing left here is for someone to do the same for `lyapunovs`. I have done it for all `lyapunov`.

**Comment by Datseris** [comment]
We decided to not implement this.
