### ISSUE TITLE
Unclear description of Joint recurrence plot functions (in RecurrenceAnalysis.jl)

### ISSUE THREAD

**Issue by RP-pbm** [JuliaDynamics/DynamicalSystems.jl#210]
**JRP**
In https://juliadynamics.github.io/RecurrenceAnalysis.jl/dev/rplots/#RecurrenceAnalysis.JointRecurrenceMatrix 
Joint recurrence plot (JRP) defined as the matrix constructed by element-wise multiplication of two distance matrices, and the binarization threshold applied after. Correct JRP by definition (https://doi.org/10.1016/j.physrep.2006.11.001, eq. 39) should be made by logical multiplication of two (or more) RPs, which are constructed with two (or more) threshold values.
May someone clarify or extend this section.

**Comment by Datseris** [comment]
The docstring says:

> . It is calculated by the element-wise multiplication of the recurrence matrices of x and y. If x and y are of different length, the recurrences are only calculated until the length of the shortest one.

So I am not sure where you read the statement "the binarization threshold applied after". As far as I can tell the docstring is clear, feel free to do a PR that somehow improves it though!

**Comment by Datseris** [comment]
The function does do the "correct" definition, logical multiplication.

**Comment by RP-pbm** [comment]
> So I am not sure where you read the statement "the binarization threshold applied after".

Sorry, I misread. But I guessed late binarization, because only one epsilon is used as a parameter: ```JointRecurrenceMatrix(x, y, ε; kwargs...)```

**Comment by Datseris** [comment]
yes: https://github.com/JuliaDynamics/RecurrenceAnalysis.jl/issues/147
