### ISSUE TITLE
Update interactive_poincaresos to v3

### ISSUE THREAD

**Issue by hisacro** [JuliaDynamics/DynamicalSystems.jl#220]
Since interactive_poincaresos is absorbed into DynamicalSystems from julia-1.9, encountering argument errors for 
differential equation keywords

example is taken from [documentation of interactive poincare sections](https://juliadynamics.github.io/DynamicalSystems.jl/dev/visualizations/#Interactive-Poincar%C3%A9-Surface-of-Section)

running the documented script with `using GLMakie, OrdinaryDiffEq, DynamicalSystems` since interactive_poincaresos is in 
InteractiveDynamics package as well.

yields, 

```
 interactive_poincaresos(::Any, ::Any, ::Any, ::Any; direction, tfinal, rootkw, color, scatterkwargs, labels, diffeq) got unsupported keyword arguments "alg", "abstol", "reltol"
   @ DynamicalSystemsVisualizations ~/.julia/packages/DynamicalSystems/cuQyu/ext/src/poincareclick.jl:3
```
the keyword 'diffeq' that was given to interactive_poincaresos  `diffeq = (alg = Vern9(), abstol = 1e-9, reltol = 1e-9)`

system status

```

Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores



Status `~/.julia/environments/v1.9/Manifest.toml`
  [f3fd9213] Attractors v1.12.0
  [608a59af] ChaosTools v3.1.1
  [ab4b797d] ComplexityMeasures v2.8.0
  [5732040d] DelayEmbeddings v2.7.3
  [61744808] DynamicalSystems v3.2.2
  [6e36e845] DynamicalSystemsBase v3.4.1
  [4665ce21] FractalDimensions v1.7.3
  [31e2f376] PredefinedDynamicalSystems v1.2.0
  [639c3291] RecurrenceAnalysis v2.0.5
  [40b095a5] StateSpaceSets v1.4.4
  [c804724b] TimeseriesSurrogates v2.6.2
```

**Comment by Datseris** [comment]
Yeah, `diffeq` is now a keyword that you need to give directly to `CoupledODEs` while constructing the dynamical system, as per the update to DynamicalSystems.jl v3+

**Comment by hisacro** [comment]
so how can I run given example, I have not given diff argument

julia> state, scene = interactive_poincaresos(hh, plane, (2, 4), complete;
       labels = ("q₂" , "p₂"),  color = λcolor )
ERROR: this function has not yet been updated to DynamicalSystems.jl v3.0. PR welcomed!
Stacktrace:


I Have read all over the documents, it's not clear how to make this work

**Comment by Datseris** [comment]
Oh, yeah, sorry. Please read the error message:

>  ERROR: this function has not yet been updated to DynamicalSystems.jl v3.0. PR welcomed!

Someone needs to update the function. To make this work you need to make a Pull Request solving it.
