### ISSUE TITLE
'g' or 'G'?

### ISSUE THREAD

**Issue by cormullion** [JuliaDynamics/DynamicalSystems.jl#24]
I wondered why it's `g` in the kwargs but `G` in the function body?

```julia
function double_pendulum(u0=rand(4); g=10.0, L1 = 1.0, L2 = 1.0, M1 = 1.0, M2 = 1.0)
...
du[2] = (M2*L1*state[2]*state[2]*sin(del_)*cos(del_) +
               M2*G*sin(state[3])*cos(del_) +
               M2*L2*state[4]*state[4]*sin(del_) -
               (M1 + M2)*G*sin(state[1]))/den1
...
```

**Comment by Datseris** [comment]
Because I am stupid, obviously!

Do you want to submit a PR to fix it and get your name in the contributors!!!!?????? Pretty appealing, right?

If not, I will fix it tonight :D

**Comment by cormullion** [comment]
Yes! That would be cool. :)

**Comment by cormullion** [comment]
Fixed by https://github.com/JuliaDynamics/DynamicalSystems.jl/pull/25.
