### ISSUE TITLE
Rename `timeseries` to `trajectory` ?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalSystems.jl#26]
Makes sense or not?

**Comment by Datseris** [comment]
This is a good change. I will do it soon I hope.

It will make the docs clearer, because it will allow all multidimensional timeseries to simply be referred to as "trajectories" while any monodimensional to be referred to as "timeseries".

**Comment by ChrisRackauckas** [comment]
Makes sense to me.

**Comment by Datseris** [comment]
Fixed by #43
