### ISSUE TITLE
is a Functor better than repeated closures?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalSystems.jl#56]
There are two ways to create an e.g. `ContinuousDS`. One is to use closures, like it is done for almost all systems:

```julia
function roessler(u0=rand(3); a = 0.2, b = 0.2, c = 5.7)
    @inline @inbounds function eom_roessler!(du, u)
        du[1] = -u[2]-u[3]
        du[2] = u[1] + a*u[2]
        du[3] = b + u[3]*(u[1] - c)
    end
    i = one(eltype(u0))
    o = zero(eltype(u0))
    J = zeros(eltype(u0), 3, 3)
    J[1,:] .= [o, -i,      -i]
    J[2,:] .= [i,  a,       o]
    J[3,:] .= [u0[3], o, u0[1] - c]
    @inline @inbounds function jacob_roessler!(J, u)
        J[3, 1] = u[3]; J[3,3] = u[1] - c
    end
    name = "Roessler76 system (a=$(a), b=$(b), c=$(c))"
  return ContinuousDS(u0, eom_roessler!, jacob_roessler!, J; name = name)
end
```
The thing with this approach is that when one wants to change parameters, one needs to create a completely new instance of `ContinuousDS` because the enclosing function has to be called:
`ds = rossler(; a = 5)`. Maybe this is extremely inefficient.

A second way to do it is to make a Functor, e.g.:
```julia
truct Lorenz96{T <: Real} # Structure with the parameters of Lorenz96 system
  F::T
  N::Int
end
# Equations of motion 
@inbounds function (obj::Lorenz96{T})(dx, x) where T
  N, F = obj.N, obj.F
  # 3 edge cases
  dx[1] = (x[2] - x[N - 1]) * x[N] - x[1] + F
  dx[2] = (x[3] - x[N]) * x[1] - x[2] + F
  dx[N] = (x[1] - x[N - 2]) * x[N - 1] - x[N] + F
  # then the general case
  for n in 3:(N - 1)
    dx[n] = (x[n + 1] - x[n - 2]) * x[n - 1] - x[n] + F
  end
  return dx
end

"""
    lorenz96(N::Int, u0 = rand(M); F=0.01)
`N` is the chain length, `F` the forcing. Jacobian is created automatically.
"""
function lorenz96(N::Int, u0 = rand(N); F=0.01)
    name = "Lorenz96 system, chain of $N (F = $(F))"
    lor96 = Lorenz96(F, N) # create struct
    return ContinuousDS(u0, lor96; name = name)
end
```

Becauses `Lorenz96` is a mutable type, after the first creation of `ds = lorenz96(5; F = 0.2)` 
one could then simply do `ds.eom!.F = 23.4` to change the `F` parameter, without needing to re-create a dynamical system instance.

In a recent update I have made all `DynamicalSystem` types to be immutable instead. But still, maybe it is worth it to make this change and use functors everywhere?

Maybe @ChrisRackauckas has something to add here? Have you had this dilemma somewhere in DiffEq where you wondered "closure vs functor" ? I know that Julia translates all closures into functors but that pretty much creates a new instance of the functor each time.

**Comment by ChrisRackauckas** [comment]
I pretty much always use callable types for this, except in cases where I know I want to change the enclosed types due to dual numbers. One thing I have to note is that supporting it as `.F` makes it less generic, which can be rough to deal with with optimizers (requiring code looping over or generating over `getfield`). These days I like everything being uniform via `ParameterizedFunction(f,params)`, which is a callable type that encloses a function, and sticks all of the parameters into one thing. If the user wants names for parameters, they can use something like a NamedTuple to hold the parameters, or you can do that behind the scenes here.

**Comment by Datseris** [comment]
I haven't perfectly understood you, which makes me think I probably was not clear enough.

First things first: `DynamicalSystems` will not care about the parameters or change them internally. Why are you saying that `.F` makes it less generic? This will only ever be done from the users, e.g.:
```julia
using DynamicalSystems
ds = Systems.lorenz() # this is a line from the package
for β in 2:0.1:10
ds.eom!.β = β # this is NOT from the package
λ = lyapunov(ds, 10) # this a line from the package
end
```

Secondly, to use `ParameterizedFunction` I would have to do an explicit interfaces that allows for one extra argument (`params`) for any function call. Or not? Because if I use `pf.p = ...` (as in the documentation for ParameterizedFunctions`, then is this any different than the above case?

Thirdly, how will `ParameterizedFunction` avoid this optimization obstacles that you mentioned (if it does). Is it worth it here for my case? I read through the README, but it is not so obvious to me as to which are the advantages of using `pf` in the current case. Of course it is obvious for DiffEq since parameter estimation is a big deal etc.

Thanks for the comments by the way! Appreciate it!

**Comment by ChrisRackauckas** [comment]
No, I wasn't saying you should used `ParameterizedFunction`s for this. I was saying a similar strategy (which is not the macro btw). 

>First things first: DynamicalSystems will not care about the parameters or change them internally.

Then `.F` and all of that is fine. Callable types is the right way to go then.

**Comment by Datseris** [comment]
Great thanks for the feedback. I was also thinking about it for months and I was always displeased with the current approach (the fact that change of parameter requires a direct re-construction of a type).

I will implement this now, and change all the example system and the docs. let's see how long it will take...

**Comment by Datseris** [comment]
On another note, do you still stand that for e.g.  a Jacobian having something like `pf(Type{Val{:jac}}, args...)` is the way to go?

Since jacobians are also crucial, I was thinking allowing the users to do:
```julia
stuct Syststem
a::Float64
end
function (f::System)(du::Vector, u::Vector)
# here are eom
end
function (f::System)(J::Matrix, u::Vector)
# here is the jacob
end
```
I am aware that this cannot allow states that are matrices, but this is in general impossible for DynamicalSystems.

**Comment by ChrisRackauckas** [comment]
No, I am instead building a type for functions in the future. 

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/diffeqfunction.jl
https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/52

It's very involved and likely overkill for your case.

**Comment by Datseris** [comment]
This is implemented and also the suggested behavior as of version 0.7
