### ISSUE TITLE
Multichannel SSA extension to Broomhead and King

### ISSUE THREAD

**Issue by finmod** [JuliaDynamics/DynamicalSystems.jl#60]
First, congratulations on how good DynamicalSystems is becoming. This work in Julia is amazing.

In nlts.jl the extension of reconstruction to Broomhead and King is really convincing and fast. 
Since the pratitioner's starting point is always a dataset, it would be good to determine if the three times series from a given synthetic dataset (in your example gissinger + noise) come from either the same model or from three different models. At present, you apply separate SSA to each time series and then determine that tau=30 in each case. Can you extend SSA to Multichannel SSA   https://arxiv.org/pdf/1309.5050 to complete the demonstration and bring to Julia a diagnostic tool already available in R.

**Comment by Datseris** [comment]
This issue was moved to JuliaDynamics/ChaosTools.jl#23
