### ISSUE TITLE
Add a section "related software" in the docs

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalSystems.jl#78]
We should have a section of "related software" in the first page of the documentation, right after the `Contacting` section.

@kahaaga I just saw all the packages around the `CausalityTools` you're developing and I was really happy to see interop with DynamicalSystems.jl. Once we have a documentation up and running please be sure to put your stuff in this "related software" section!

**Comment by kahaaga** [comment]
@Datseris Sure will do! I am in the processes of upgrading all the dependencies for `CausalityTools` to run with Julia 1.0. That should be finished soon. Once everything is released and the documentation is finished, I'll submit a PR for the "related software" section.
