### ISSUE TITLE
Add progress bar / ETA for all time consuming functions

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalSystems.jl#8]
This should be added to all functions, from `evolve` and `timeseries` to `lyapunovs` etc..

Also, it should be done in two ways: first for Juno using the innate progress bar that has been set up, 
and also for the REPL, using [`ProgressMeter.jl`](https://github.com/timholy/ProgressMeter.jl).

I suggest to simply create a `progress(n, N, message)` function that displays the message and the progress based on `n` which should go up to `N`. This function should know/be configured to decide whether to use Juno or ProgressMeter.

After this is done it is easy to put it on all functions!

**Comment by ChrisRackauckas** [comment]
I think we are both looking for this:

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/121
https://github.com/JunoLab/Juno.jl/issues/29

Maybe we can convince @pfitzseb to do it 👍

**Comment by Datseris** [comment]
oh nice that more people want this! Seems natural to be honest.

**Comment by asinghvi17** [comment]
ProgressMeter.jl is now integrated with Juno.

**Comment by asinghvi17** [comment]
This is actually possible with debug messages (and is integrated into Juno):
```julia
ENV["JULIA_DEBUG"] = "Main" # change this to DynamicalSystems, DrWatson, etc.
for i in 1:100
    @debug "looping" progress=i/100
    sleep(0.1)
end
```
If you paste this into the Juno REPL, it will show a progress bar on the bottom left.

I'm not sure what REPL-based solution this integrates with, but there's no need for a dependency or anything (unless we want it, to make life easier).

**Comment by Datseris** [comment]
Thanks. Actually I closed this because there aren't any "time consuming functions" anymore. The time consumption comes from looping over parameters values or initial conditions. But in this case I think it is better if the progress bar comes from the User's side, using e.g. the code you provide, (or just `println` which is what I do atm).
