### ISSUE TITLE
Switch to new version registration process

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/DynamicalSystems.jl#89]
Shall we install the Registrator app in JuliaDynamics to adapt to the new registration process?

Cf.:
https://juliaregistrator.github.io/
https://discourse.julialang.org/t/switching-package-registration-systems-on-monday/22677

**Comment by Datseris** [comment]
Yeap. I've installed the Registrator App in all of our repos, so in principle we don't have to do anything more besides "adapting to the new release process" (i.e. commenting on pull requests / issues).

**Comment by heliosdrm** [comment]
Great! But it is also necessary to add a `Project.toml` in each repo before registering in the new framework, isn't it? (And drop `REQUIRE`, if we want to keep the repositories tidy.)

**Comment by Datseris** [comment]
Yeap, in fact there are many steps that are necessary:

1. Create Project.toml
2. Add all the UUIDs there (which is a huge amount of work)
3. Add test dependencies on Project.toml
4. Remove REQUIREs
5. Spend a lot of time bugfixing this.

I just did all 5 of these steps for another package I want to soon beta-release (DrWatson) and it was not fun at all, and took much more time than it reasonably should.

Someone is making a script for automatic convertion of REQUIRE to Project.toml. I will wait for that before doing any extra work.

(plus I think we are at the quite comfortable spot of not having to release a new version anytime soon)

**Comment by asinghvi17** [comment]
Thia should be closed AFAICT?
