### ISSUE TITLE
Using a ContinuousCallback with DynamicalSystems

### ISSUE THREAD

**Issue by bojohnson02** [JuliaDynamics/DynamicalSystems.jl#93]
# Issue description
I've set up my system with the dynamical equations (eom), the jacobian, and followed DifferentialEquations on setting up a callback. When running `trajectory()` however, the `affect!()` function for the callback throws an error because it doesn't work with StaticArrays. I'm confused then as to how I'm supposed to use callbacks if I can't set up a ContinuousDynamicalSystem without a StaticArray.

# Expected behavior
`trajectory()` is able to integrate the ContinuousDynamicalSystem with the callback.

# MWE
Here's my code, sorry about the ugly jacobian
```
using DynamicalSystems, DifferentialEquations
using StaticArrays

function makedipole(s, E)
    pr2 = abs(2*E+(cos(s[3])+3*cos(s[3]-2s[2]))/(6s[1]^3)-s[5]^2/s[1]^2-10s[6]^2)
    s[4] = sqrt(pr2)

    return s
end

E = -0.0215383
initstate = [1.0,0.0,0.0,0.0,-0.1966,0.148631]
state = SVector{6}(makedipole(initstate, E))

function eom(x, p, t)
    dx = zeros(6)
    dx[1] = x[4]
    dx[2] = x[5]/x[1]^2
    dx[3] = 10*x[6]
    dx[4] = x[5]^2/x[1]^3-3*(cos(x[3])+3*cos(x[3]-2*x[2]))/(12*x[1]^4)
    dx[5] = sin(x[3]-2*x[2])/(2*x[1]^3)
    dx[6] = -(sin(x[3])+3*sin(x[3]-2*x[2]))/(12*x[1]^3)

    return SVector{6}(dx)
end

function condition(x, t, integrator)
    x[1] - 1
end

function affect!(integrator)
    integrator.u[4] = -integrator.u[4]
end

cb = ContinuousCallback(condition,affect!)

function jacobian(x, p, t)
    J = @SMatrix [0 0 0 1 0 0;
                  -2*x[5]/x[1]^3 0 0 0 1/x[1]^2 0;
                  0 0 0 0 0 10;
                  -3*x[5]^2/x[1]^4+(3*cos(2*x[2]-x[3])+cos(x[3]))/x[1]^5 3*sin(2*x[2]-x[3])/(2*x[1]^4) -(3*sin(2*x[2]-x[3])-sin(x[3]))/(4*x[1]^4) 0 2*x[5]/x[1]^3 0;
                  3*sin(2*x[2]-x[3])/(2*x[1]^4) -cos(2*x[2]-x[3])/x[1]^3 cos(2*x[2]-x[3])/(2*x[1]^3) 0 0 0;
                  -(3*sin(2*x[2]-x[3])-sin(x[3]))/(4*x[1]^4) cos(2*x[2]-x[3])/(2*x[1]^3) (-3*cos(2*x[2]-x[3])-cos(x[3]))/(12*x[1]^3) 0 0 0]

    return J
end

ds = ContinuousDynamicalSystem(eom, state, nothing, jacobian)

trajectory(ds, 20.0, callback=cb, dt=1e-4, alg=Tsit5())
```
The error when run is `setindex!(::SArray{Tuple{6},Float64,1,6}, value, ::Int) is not defined.` and it happens inside `affect!()`.

Let me know if there's context I can provide for this problem I'm working on, or if I should include other information about the error. This is my first time using DynamicalSystems.jl.

**Comment by Datseris** [comment]
Hi @bojohnson02 . This question is in fact not really related with DynamicalSystems.jl.

Of course, if you want to use a callback that mutates the state on the spot you should use the in-place version of `DynamicalSystem`. You state:

> how I'm supposed to use callbacks if I can't set up a ContinuousDynamicalSystem without a StaticArray.

This is incorrect. **It is possible** to create `DynamicalSystem` without static arrays, see here: https://juliadynamics.github.io/DynamicalSystems.jl/dev/ds/general/#discrete-in-place

But, in your case, there is an even better option that allows you to still use static arrays since your system has small dimension. Just change `affect!` to change the entire state like so:

```julia
function affect!(integrator)
    u = integrator.u
    integrator.u = SVector(u[1], u[2], u[3], -u[4])
end
```

**Comment by bojohnson02** [comment]
Thank you, that helped solve my problem.
