### ISSUE TITLE
`jacobian!(xnew, x, p, n)` should be `jacobian!(xnew, x, p, n)`

### ISSUE THREAD

**Issue by yuxiliu1995** [JuliaDynamics/DynamicalSystems.jl#97]
From [Dynamical System Definition - DynamicalSystems.jl](https://juliadynamics.github.io/DynamicalSystems.jl/latest/ds/general/#discrete-in-place)

> The optional argument `jacobian` for the constructors is a *function* and (if given) must also be of the same form as the `eom`, `jacobian(x, p, n) -> SMatrix` for the out\-of\-place version and `jacobian!(xnew, x, p, n)` for the in\-place version.

Should be 
> `jacobian!(Jnew, x, p, n)`

Also, in the Definition Table, the entry
> `eom!(du, u, p, t)`
only makes sense for continuous systems. For discrete systems, it should be 
> `eom!(unew, u, p, t)`

Further, it might be noted that since Julia is pass-by-value, if the dynamical system is 1-dimensional, and its state space is represented by naked numbers, then it would be impossible to write in-place forms.

**Comment by yuxiliu1995** [comment]
Also, after some experimentation, I think the system doesn't expect any ContinuousDynamicalSystem to use naked numbers, even if the system has dimension 1. 

To see it, try this:
```julia
using DynamicalSystemsBase
exp_eom(x, p, t) = x
exp_jacob(x, p, t) = 1.0
exp_sys = ContinuousDynamicalSystem(exp_eom, 0.1, nothing, exp_jacob)

tr = trajectory(exp_sys, 100.0, dt = 0.005, Ttr = 50.0)
```
throws error 
```
MethodError: no method matching _initialize_ks(::Float64)
Closest candidates are:
  _initialize_ks(!Matched::Array{#s110,1} where #s110<:(AbstractArray{T,1} where T)) at C:\Users\Yuxi\.julia\packages\SimpleDiffEq\fQUcj\src\tsit5\atsit5.jl:127
  _initialize_ks(!Matched::AbstractArray{T,N} where N) where T<:Number at C:\Users\DeadScholar\.julia\packages\SimpleDiffEq\fQUcj\src\tsit5\atsit5.jl:125
```

**Comment by Datseris** [comment]
Yeap, that is true and maybe we should document it better. 1D continuous systems are not supported in the oop form, and its certainly not worth the effort to support them.
