### ISSUE TITLE
[doc] Add animated stroboscopic plot of Duffing oscillator

### ISSUE THREAD

**Issue by yuxiliu1995** [JuliaDynamics/DynamicalSystems.jl#99]
```julia
using DynamicalSystems, Plots

ds = Systems.duffing(β = -1, ω = 1, f = 0.3) # non-autonomous chaotic system

frames=120
a = trajectory(ds, 100000.0, dt = 2π/frames, Ttr=20π) # every period T = 2π/ω

orbit_length = div(size(a)[1], frames)
a = Matrix(a)

@gif for i in 1:frames
    orbit_points = i:frames:(orbit_length*frames)
    scatter(a[i:frames:(orbit_length*frames), 1], a[i:frames:(orbit_length*frames), 2], markersize=1, html_output_format=:png, 
        leg=false, framestyle=:none, xlims=extrema(a[:,1]), ylims=extrema(a[:,2]))
end
```
gives 
![Duffing stroboscopic plot](https://user-images.githubusercontent.com/33951560/71765418-70c2bb80-2f2f-11ea-9295-ca672849334b.gif)

**Comment by Datseris** [comment]
This piece of code saves the gif somewhere? How will it be displayed in the documentation? In general, we try to store all videos/gifs that need to be saved in this folder: https://github.com/JuliaDynamics/JuliaDynamics/tree/master/videos/chaos 

(so that installation of `DynamicalSystems` is as lean as possible)

**Comment by yuxiliu1995** [comment]
The code, if run in Jupyter, saves the animation as `tmp.gif` in the working directory, as well as displays it in the notebook.

I just think it would be neat to look like this
https://docs.juliaplots.org/latest/

**Comment by Datseris** [comment]
Yeap that is straightforward. Just upload the `gif` image to the folder I've linked above, and I'll take it from there!

**Comment by yuxiliu1995** [comment]
In https://juliadynamics.github.io/DynamicalSystems.jl/latest/chaos/orbitdiagram/#stroboscopic-map
I just noticed that the line `orbit_points = i:frames:(orbit_length*frames)` is useless leftover code that missed my attention. Sorry. 
Can you remove it?

**Comment by Datseris** [comment]
https://github.com/JuliaDynamics/DynamicalSystems.jl/commit/e329258c1229e48dd959fa105b43ed700c97c58d
